plugins {
    id 'com.android.application'
}

android {
    namespace 'th.co.baac.smartoutlet'
    compileSdk 36

    defaultConfig {
        applicationId "th.co.baac.smartoutlet"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
